#!/bin/bash -l

# Check that updates have been made to `hashicups/resource_order.go`
if ! grep -q 'c.DeleteOrder(orderID)' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to update 'resourceOrderDelete' function in '$RESOURCE_ORDER_FILE' using the code example."
    exit 1
fi

# Check the user ran 'terraform destroy'
grep -q "terraform destroy --auto-approve" '$BASH_HISTORY_FILE' || fail-message "You haven't run 'terraform destroy --auto-approve' yet."

# Confirm the order has been destroyed
TF_OUT_JSON=$(terraform output -json)
if ! [ "$TF_OUT_JSON" = "{}" ]; then
    fail-message "You did not successfully run terraform destroy."
    exit 1
fi
