#!/bin/bash -l

export PROJECT_HOME_DIR="/root/github.com/hashicorp/terraform-provider-hashicups/"

cd $PROJECT_HOME_DIR
git checkout implement-update

cd $PROJECT_HOME_DIR/examples
rm .terraform.lock.hcl

# Set the working directory to the project home
set-workdir $PROJECT_HOME_DIR

exit 0
