#!/bin/bash -l

# Check out the branch with all the correct files
cd /root/github.com/hashicorp/terraform-provider-hashicups/
git checkout implement-delete

# Install the provider
make install

# Initialize and apply
cd /root/github.com/hashicorp/terraform-provider-hashicups/examples
terraform init && terraform apply -auto-approve

# TODO: confirm the delete
# curl -X GET -H "Authorization: ${HASHICUPS_TOKEN}" localhost:19090/orders/1

exit 0
