#!/bin/bash -l

git checkout implement-read

# Remove the .terraform.lock.hcl file and statefile from the last challenge
cd /root/github.com/hashicorp/terraform-provider-hashicups/examples
rm -rf .terraform
rm .terraform.lock.hcl

exit 0