#!/bin/bash -l

export PROJECT_HOME_DIR="/root/github.com/hashicorp/terraform-provider-hashicups/"

cd $PROJECT_HOME_DIR
git checkout implement-read

# Remove terraform lock from previous challenge
cd /root/github.com/hashicorp/terraform-provider-hashicups/examples
rm .terraform.lock.hcl

# Set the working directory to the project home
set-workdir $PROJECT_HOME_DIR

exit 0
