#!/bin/bash -l

# Check that updates have been made to `hashicups/resource_order.go`
if ! grep -q 'ResourceImporter' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to update the 'resourceOrder' function in 'hashicups/resource_order.go' using the code example."
    exit 1
fi

if [ ! -f $TF_IMPORT_MAIN_FILE ]; then
    fail-message "You have not created the 'main.tf' file under the 'examples/import' directory yet."
    exit 1
fi

# TODO: check the contents of the main.tf file

# TODO: check the state file and see that something has been imported - currently this stage does not work
