#!/bin/bash -l

# Check out the branch with all the correct files
cd $PROJECT_HOME_DIR
git checkout implement-import

# Install the provider
make install

# Initialize the terraform config
cd $PROJECT_HOME_DIR/examples/import
terraform init

# Create a new order
curl -X POST -H "Authorization: ${HASHICUPS_TOKEN}" localhost:19090/orders -d '[{"coffee": { "id":1 }, "quantity":4}, {"coffee": { "id":3 }, "quantity":3}]'

# Import the order that was created
# TODO: get the right ID
terraform import hashicups_order.sample 3

# Confirm the order has been imported properly
terraform state show hashicups_order.sample

exit 0
