#!/bin/bash -l

# Check out the branch with all the correct files
cd $PROJECT_HOME_DIR
git checkout implement-import

# Install the provider
make install

# Initialize the terraform config
cd $PROJECT_HOME_DIR/examples/import
terraform init

exit 0
