#!/bin/bash -l

RESOURCE_ORDER_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/resource_order.go

# Check `hashicups/resource_order.go` exists
if ! test -f "$RESOURCE_ORDER_FILE"; then
    fail-message "You haven't created 'hashicups/resource_order.go' yet."
    exit 1
fi

# Check all the expected updates have been mamde to `hashicups/resource_order.go`
if ! grep -q 'resourceOrder' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'resourceOrder' function to 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'resourceOrderCreate' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'resourceOrderCreate' function to 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'resourceOrderRead' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'resourceOrderRead' function to 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'resourceOrderUpdate' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'resourceOrderUpdate' function to 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'resourceOrderDelete' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'resourceOrderDelete' function to 'hashicups/resource_order.go'."
    exit 1
fi

# TODO: Check that the schema was updated properly

# TODO: check that the resourceOrderCreate function was implemented (not just present)
# TODO: check that the resourceOrderRead function was implemented (not just present)
# TODO: check that the flattenOrderItems function was implemented (not just present)
# TODO: check that the flattenCoffee function was implemented (not just present)
# TODO: check that resourceOrderRead is in the resourceOrderCreate function
# TODO: checl that the order resource has been added to the provider`


# Check `hashicups/resource_order.go` has the new imports
if ! grep -q 'github.com/hashicorp-demoapp/hashicups-client-go' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'github.com/hashicorp-demoapp/hashicups-client-go' import to 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'strconv' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'strconv' import to 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'items' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'items' schema to 'hashicups/resource_order.go'."
    exit 1
fi


# TODO: check that the new resource was created in the TF state ouptputs