#!/bin/bash -l

# Check out the previous branch to make sure everything is as we expect
cd $PROJECT_HOME_DIR
git checkout debug-tf-providers

# Remove terraform lock from previous challenge
cd $PROJECT_HOME_DIR/examples
rm .terraform.lock.hcl

# Set the working directory to the project home
set-workdir $PROJECT_HOME_DIR

exit 0
