#!/bin/sh

# TODO: put these in bashrc along with all other file paths used in the scripts
PROJECT_HOME_DIR="/root/github.com/hashicorp/terraform-provider-hashicups/"
echo "export PROJECT_HOME_DIR=$PROJECT_HOME_DIR" >> /root/.bashrc

MOD_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/go.mod
MODTEXT_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/vendor/modules.txt
echo "export MOD_FILE=$MOD_FILE" >> /root/.bashrc
echo "export MODTEXT_FILE=$MODTEXT_FILE" >> /root/.bashrc

BASH_HISTORY_FILE=/root/.bash_history
BASHRC_FILE=/root/.bashrc
echo "export BASH_HISTORY_FILE=$BASH_HISTORY_FILE" >> /root/.bashrc
echo "export BASHRC_FILE=$BASHRC_FILE" >> /root/.bashrc

PROVIDER_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/provider.go
PROVIDER_BINARY_FILE=/root/.terraform.d/plugins/hashicorp.com/edu/hashicups/0.2/linux_amd64/terraform-provider-hashicups
echo "export PROVIDER_FILE=$PROVIDER_FILE" >> /root/.bashrc
echo "export PROVIDER_BINARY_FILE=$PROVIDER_BINARY_FILE" >> /root/.bashrc

DATA_SOURCE_COFFEE_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/data_source_coffee.go
DATA_SOURCE_ORDERS_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/data_source_order.go
echo "export DATA_SOURCE_COFFEE_FILE=$DATA_SOURCE_COFFEE_FILE" >> /root/.bashrc
echo "export DATA_SOURCE_ORDERS_FILE=$DATA_SOURCE_ORDERS_FILE" >> /root/.bashrc

RESOURCE_ORDER_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/resource_order.go
echo "export RESOURCE_ORDER_FILE=$RESOURCE_ORDER_FILE" >> /root/.bashrc

TF_DIR=/root/github.com/hashicorp/terraform-provider-hashicups/examples
TF_MAIN_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/examples/main.tf
echo "export TF_DIR=$TF_DIR" >> /root/.bashrc
echo "export TF_MAIN_FILE=$TF_MAIN_FILE" >> /root/.bashrc

###########
# Install Docker Compose and Docker
###########
apt-get update
apt install -y docker-compose docker.io

sudo systemctl unmask docker
sudo systemctl start docker

###########
# Install Golang 1.11+ to use with Go Modules
###########
GO_VERSION="1.16.3"
wget https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz
rm -rf /usr/bin/go && tar -C /usr/bin -xzf go$GO_VERSION.linux-amd64.tar.gz
rm go$GO_VERSION.linux-amd64.tar.gz

PATH=$PATH:/usr/bin/go/bin
GOPATH=/root
echo "export PATH=$PATH:/usr/bin/go/bin" >> /root/.bashrc
echo "export GOPATH=$GOPATH" >> /root/.bashrc

###########
# Install a Docker Compose version > 1.25.5
###########
DOCKER_COMPOSE_VERSION="1.29.1"
rm /usr/bin/docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose

###########
# Set up the development environment
###########

mkdir -p /root/github.com/hashicorp/
cd /root/github.com/hashicorp/
# git clone --branch boilerplate https://github.com/hashicorp/terraform-provider-hashicups
git clone --branch boilerplate https://github.com/dahlke/terraform-provider-hashicups

###########
# Start the HashiCups Application
###########
cd $PROJECT_HOME_DIR/docker_compose
docker-compose up -d

###########
# Install VS Code Server
###########
curl -fsSL https://code-server.dev/install.sh | sh

# Create a unit file for VS Code server
cat <<-EOF > /etc/systemd/system/code-server.service
[Unit]
Description=Code Server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=simple
Restart=always
RestartSec=1
User=root
ExecStart=/usr/bin/code-server --host 0.0.0.0 --port 8443 --cert --auth none /root/github.com/hashicorp/terraform-provider-hashicups/
[Install]
WantedBy=multi-user.target
EOF

# Enable and start VS Code server
systemctl enable code-server
systemctl start code-server

# Set the working directory to the project home
set-workdir $PROJECT_HOME_DIR

exit 0
