#!/bin/sh

###########
# Set up the development environment
###########
git clone --branch boilerplate https://github.com/hashicorp/terraform-provider-hashicups


###########
# Install Docker Compose
###########
apt-get update
apt install -y docker-compose

exit 0
