#!/bin/sh

###########
# Install Docker Compose and Docker
###########

# TODO: need to change the compose version to  match the Docker version
# https://docs.docker.com/compose/compose-file/compose-versioning/

apt-get update
apt install -y docker-compose docker.io

sudo systemctl unmask docker
sudo systemctl start docker

###########
# Install Golang 1.11+ to use with Go Modules
###########
# TODO: parameterize this or bake it into the image
wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
rm -rf /usr/bin/go && tar -C /usr/bin -xzf go1.16.3.linux-amd64.tar.gz

export PATH=$PATH:/usr/bin/go/bin
export GOPATH=/root
echo "export PATH=$PATH:/usr/bin/go/bin" >> /root/.bashrc
echo "export GOPATH=/root" >> /root/.bashrc

###########
# Install a Docker Compose version > 1.25.5
###########
rm /usr/bin/docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose


###########
# Set up the development environment
###########

mkdir -p /root/github.com/hashicorp/
cd /root/github.com/hashicorp/
# TODO: git clone --branch boilerplate https://github.com/hashicorp/terraform-provider-hashicups
git clone --branch boilerplate https://github.com/dahlke/terraform-provider-hashicups

###########
# Start the HashiCups Application
###########
cd /root/github.com/hashicorp/terraform-provider-hashicups/docker_compose
docker-compose up -d


# TODO: set the cwd to the provider repo

exit 0
