#!/bin/bash -l

# Check out the branch with all the correct files
cd /root/github.com/hashicorp/terraform-provider-hashicups
git checkout implement-read

# Initialize the module for our provider and install the dependencies.
go mod init terraform-provider-hashicups
go mod vendor

# Install the provider
make install

exit 0
