#!/bin/bash -l

RESOURCE_ORDER_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/resource_order.go
TF_MAIN_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/examples/main.tf

if ! grep -q 'last_updated' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'last_updated' schema to the 'resourceOrder' 'hashicups/resource_order.go'."
    exit 1
fi

if ! grep -q 'time' "$RESOURCE_ORDER_FILE"; then
    fail-message "You need to add the 'time' import to the 'resourceOrder' 'hashicups/resource_order.go'."
    exit 1
fi

# Check the `main.tf` file has the update quantity within the hashicups_order resource
if ! grep -q 'quantity = 3' "$TF_MAIN_FILE"; then
    fail-message "You need to change the quantity from 2 to 3 in the 'hashicups_order' resource in 'examples/main.tf'."
    exit 1
fi
