#!/bin/bash -l

# Check out the branch with all the correct files
cd $PROJECT_HOME_DIR
git checkout implement-update

# Install the provider
make install

# Initialize and apply
cd $PROJECT_HOME_DIR/examples
terraform init && terraform apply -auto-approve

# TODO: confirm the update
# curl -X GET -H "Authorization: ${HASHICUPS_TOKEN}" localhost:19090/orders/1

exit 0
