#!/bin/bash -l

PROVIDER_FILE=/root/github.com/hashicorp/terraform-provider-hashicups/hashicups/provider.go

# TODO: Check for a bad signin after changing the environment variables in the docker-compose output

# Check for the `diags` in `providerConfigure` (`hashicups/provider.go`)
if ! grep -q 'diags = append' "$PROVIDER_FILE"; then
    fail-message "You need to add the 'diags' variable to your `providerConfigure` function in 'hashicups/provider.go'."
    exit 1
fi

# TODO: Check for a two bad signins in the docker-compose output (after adding the `diags` above)
cd ../docker_compose
DOCKER_COMPOSE_SIGNIN_LOGS=$(docker-compose logs | grep signin)
# if ! grep -q 'Handle User | signin' "$DOCKER_COMPOSE_SIGNIN_LOGS"; then
    # fail-message "There was not a successful login attempt to HashiCups."
    # exit 1
# fi

# Confirm the environment variables were reset to valid credentials
if [ "$HASHICUPS_USERNAME" = "education" ]; then
    fail-message "You did not set the 'HASHICUPS_USERNAME' to the correct value 'education'."
fi

if [ "$HASHICUPS_PASSWORD" = "test123" ]; then
    fail-message "You did not change the 'HASHICUPS_PASSWORD' to the correct value 'test123'."
fi

# TODO: Check for a good signin after changing the provider setup? In the output?
# if ! grep -q 'Handle User | signin' "$DOCKER_COMPOSE_SIGNIN_LOGS"; then
    # fail-message "There was not a successful login attempt to HashiCups."
    # exit 1
# fi