#!/bin/bash -l

# Check out the branch with all the correct files
cd /root/github.com/hashicorp/terraform-provider-hashicups/
git checkout debug-tf-provider

# Install the provider
make install

# Initialize and apply
cd /root/github.com/hashicorp/terraform-provider-hashicups/examples
terraform init && terraform apply -auto-approve

exit 0
