#!/bin/bash -l

cd $PROJECT_HOME_DIR
git checkout auth-configuration

cd $PROJECT_HOME_DIR/examples
rm .terraform.lock.hcl

# Set the working directory to the project home
set-workdir $PROJECT_HOME_DIR

exit 0
