#!/bin/bash -l

cd /root/github.com/hashicorp/terraform-provider-hashicups/
git checkout auth-configuration

cd /root/github.com/hashicorp/terraform-provider-hashicups/examples
rm .terraform.lock.hcl

exit 0
